# Generated by Django 5.1.1 on 2025-02-17 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrowYourEmpire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='wantedResource',
            field=models.IntegerField(default=0, verbose_name='Resource wanted'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='option',
            name='questionOptionText',
            field=models.CharField(max_length=150, verbose_name='Option 1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionText',
            field=models.CharField(max_length=150, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='village',
            name='god',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GrowYourEmpire.god'),
        ),
    ]
