# Generated by Django 5.1.1 on 2025-03-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrowYourEmpire', '0002_attack_wantedresource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='dailyFood',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Daily food obtained'),
        ),
        migrations.AlterField(
            model_name='village',
            name='dailyStone',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Daily stone obtained'),
        ),
        migrations.AlterField(
            model_name='village',
            name='dailyWood',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Daily wood obtained'),
        ),
    ]
