# Generated by Django 5.1.4 on 2025-04-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrowYourEmpire', '0003_alter_village_dailyfood_alter_village_dailystone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='desc',
            field=models.TextField(max_length=2000, verbose_name='Description'),
        ),
    ]
