# Generated by Django 5.1.1 on 2025-04-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrowYourEmpire', '0004_alter_new_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=models.TextField(max_length=2000, verbose_name='Description'),
        ),
    ]
