# Generated by Django 5.1.1 on 2025-05-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrowYourEmpire', '0005_alter_event_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='remainingTicks',
            field=models.IntegerField(default=0, verbose_name='Days remaining'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('desc', models.TextField(max_length=2000, verbose_name='Description')),
                ('registeredDateTime', models.DateTimeField(verbose_name='Registration date')),
                ('read', models.BooleanField(default=False, verbose_name='Read')),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('title', 'registeredDateTime'), name='Suggestion_title_registeredDateTime')],
            },
        ),
    ]
